# Generated by Django 4.2 on 2023-04-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('allow_bottom_up', models.BooleanField()),
                ('allow_one_hand', models.BooleanField()),
                ('allow_two_hands', models.BooleanField()),
                ('allow_double', models.BooleanField()),
                ('type', models.CharField(choices=[('B', 'Balistics'), ('G', 'Grind')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_count', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('date', models.DateField()),
                ('bottom_up', models.BooleanField(choices=[(False, 'Standard'), (True, 'Bottom up')], default=False)),
                ('hand', models.CharField(choices=[('1H', 'One Hand'), ('2H', 'Two hands'), ('Db', 'Double')], max_length=2)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_statistics.exercise')),
            ],
        ),
    ]
