# Generated by Django 4.2 on 2023-07-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_statistics', '0003_remove_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hand',
            field=models.CharField(choices=[('1H', 'One Hand'), ('2H', 'Two hands'), ('Db', 'Double')], default='1H', max_length=2),
        ),
    ]
