# Generated by Django 4.2 on 2023-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_statistics', '0004_alter_session_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
